development:
  adapter: postgresql
  encoding: unicode
  username: <%= `whoami` %>
  host: 127.0.0.1
  password:
  database: fam_client_development
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  username: <%= `whoami` %>
  host: 127.0.0.1
  password:
  database: fam_client_development
  min_messages: warning
  database: fam_client_test
  min_messages: warning

